version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./public:/app/public

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./voices:/app/../voices:ro  # Mount voices at the correct relative path
      - ./public:/app/public
    environment:
      - API_PORT=8000
      - API_HOST=0.0.0.0
      - DEBUG=True
    # Add healthcheck to see if API is running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s