services:
  - type: web
    name: voice-manipulation
    env: docker
    dockerfilePath: ./Dockerfile.combined
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: ""  # Empty to ensure frontend uses relative URLs
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 8000
      - key: PORT
        value: 10000
    disk:
      name: voices
      mountPath: /app/api/voices
      sizeGB: 1